# 기존에 있던 FROM nginx:alpine 유지
FROM nginx:alpine

RUN apk update && apk upgrade && \
    apk add --no-cache npm

# 인증서 복사
COPY ./certs/localhost.pem /etc/ssl/cert.pem
COPY ./certs/localhost-key.pem /etc/ssl/key.pem

COPY nginx_config/default.conf /etc/nginx/conf.d/default.conf
WORKDIR /app
RUN npm install js-cookie

WORKDIR /nginx
CMD ["nginx", "-g", "daemon off;"]
