FROM nginx:alpine

RUN apk update && apk upgrade && \
    apk add --no-cache npm openssl

COPY nginx_config/default.conf /etc/nginx/conf.d/default.conf

COPY nginx_config/nginxSetting.sh .

RUN chmod +x nginxSetting.sh && mkdir -p /etc/ssl

WORKDIR /app

RUN npm install js-cookie

WORKDIR /nginx

ENTRYPOINT ["sh", "/nginxSetting.sh"]
