spring:
  application:
    name: cinefinder

  profiles:
    active: ${PROFILE}

  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    type: redis
  data:
    redis:
      port: ${REDIS_EXTERNAL_PORT}

api:
  kobis:
    request-url: ${KOBIS_REQUEST_URL}
    service-key: ${KOBIS_SERVICE_KEY}
  kmdb:
    request-url: ${KMDB_REQUEST_URL}
    service-key: ${KMDB_SERVICE_KEY}

# =========================== LOCAL  ===========================
---
spring.config.activate.on-profile: local

server:
  port: ${LOCAL_SERVER_PORT}

spring:
  datasource:
    url: jdbc:mysql://${LOCAL_HOST}:${MYSQL_EXTERNAL_PORT}/${MYSQL_DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8

  data:
    redis:
      host: ${LOCAL_HOST}

  elasticsearch:
    uris: http://${LOCAL_HOST}:${ES_EXTERNAL_PORT_1}/
    connection-timeout: 120s
    socket-timeout: 120s

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: false


# logging
logging-level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  org.springframework.data.elasticsearch.client: debug

# =======================================  MAIN  =======================================
---
spring.config.activate.on-profile: main

server:
  port: ${MAIN_SERVER_PORT}

spring:
  datasource:
    url: jdbc:mysql://${MAIN_HOST}:${MYSQL_EXTERNAL_PORT}/${MYSQL_DB_NAME}?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8

  data:
    redis:
      host: ${MAIN_HOST}

  elasticsearch:
    uris: http://${MAIN_HOST}:${ES_EXTERNAL_PORT_1}/
    connection-timeout: 120s
    socket-timeout: 120s

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        use_sql_comments: false
---